name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      browser:
        description: 'Choose browser'
        required: false
        default: 'chromium'
        type: choice
        options:
        - chromium
      headed:
        description: 'Enable Headless mode or not'
        required: false
        default: false
        type: boolean

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox, webkit]
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright browsers
      run: npx playwright install --with-deps ${{ matrix.browser }}
    
    - name: Run Playwright tests
      run: npx playwright test --project=${{ matrix.browser }}
      env:
        CI: true
    
    - name: Upload test report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report-${{ matrix.browser }}
        path: |
          playwright-report/
          test-results/
        retention-days: 30

  notify:
    runs-on: ubuntu-latest
    needs: test
    if: always()
    
    steps:
    - name: Notify test results
      run: |
        if [ "${{ needs.test.result }}" == "success" ]; then
          echo "All tests passed!"
        elif [ "${{ needs.test.result }}" == "failure" ]; then
          echo "Tests failed, please check the report"
          exit 1
        else
          echo "Tests were cancelled or skipped"
        fi 